<?php

$moduletitle = "Help, Support and Credits";

$main_content = '

	<p><strong>Icons</strong>: <a href="http://zeus.qballcow.nl/icon/">Gartoon</a> by Zeus</p>
	<p>Language credit (autogenerated from the files)</p>
	<p>Development credit</p>

	';
?>