scratchpad:


Options:

	Plugin manager
	User management
	Templates
	knife settings
	
	
Delete multiple is broken



> autogenerated sitemap
please elaborate
> the possibility of at least 2 categories per article
ofcourse ;-) 
> to match Web Content Accessibility guidelines, it should be possible to link to <!-- more --> via the topic title. WAI requires individual links, so "more.." would not validate. At the moment in AJ 168, this is not really possible, because [full-link]...[/full-link] will only appear if there is more, if not the title is missing. [link]...[/link] does work, but creates a useless link,even if there is no extended text. So to match "13.1 Clearly identify the target of each link." the should be a possiblility to link to the full text via topic (only if there is really extended text)
I'll look into this, definately, though I'm not sure I entirely understood it
> include Filemanager, so that we can upload pdf, word etc.
plugin-functionality - yes.
> make it work even in IE
don't have ie. not possible.
> WYSIWYG Editor with option to switch to direct sourcecode editing
maybe. I really _hate_ wysiwyg stuff though, so I need some incentive
> make a switch so that articles can be hidden/approved
good idea
> backup function with gzip or so
also good idea


Eruin, let me know what you think about it.



<label for="component" accesskey="m">
  <select name="component" id="component" 
    multiple="multiple" size="10">

    <option value="4Suite">4Suite</option>
    <option value="9wm">9wm</option>
    <option value="a2ac">a2ac</option